# Generated by Django 5.2.13 on 2026-04-27 23:58

from django.db import migrations
import uuid


def handle_phone_duplicates(apps, schema_editor):
    """
    Remove duplicate phone values and assign unique ones to empty/duplicate entries.
    """
    User = apps.get_model('users', 'User')
    
    # Handle empty phone values
    empty_phone_users = User.objects.filter(phone='')
    for user in empty_phone_users:
        # Assign a unique phone based on user ID
        user.phone = f"+1{1000000000 + user.id}"
        user.save()
    
    # Handle duplicate phone values
    phone_counts = {}
    for user in User.objects.all():
        if user.phone in phone_counts:
            # Generate unique phone for duplicate
            user.phone = f"+1{1000000000 + user.id}"
            user.save()
        else:
            phone_counts[user.phone] = user.id


def reverse_handle_phone_duplicates(apps, schema_editor):
    """Reverse operation - set phone back to empty for generated ones"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(handle_phone_duplicates, reverse_handle_phone_duplicates),
    ]
